apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculatorwebapp
  labels:
    app: binarycalculatorwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculatorwebapp
  template:
    metadata:
      labels:
        app: binarycalculatorwebapp
    spec:
      containers:
      - name: binarycalculatorwebapp
        image: us-central1-docker.pkg.dev/project-ebf6c4d4-5ed4-4a81-80d/sofe3980u/binarycalculatorwebapp:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
